### ISSUE TITLE
Improve copyright statement

### ISSUE THREAD

**Issue by ethanjli** [apienc/dfp-portal#4]
The current copyright statement in the website footer needs to be improved to acknowledge details/nuances and add acknowledgement of Storycorps SF as appropriate. Who do we need to ask to improve the copyright statement?

## Implementation Notes
The copyright statement needs to be edited in the [functions.php](https://www.dragonfruitproject.org/wp-admin/theme-editor.php?file=inc%2Ffunctions.php&theme=DFPBestTheme) file - in that file, search for `colormag_footer_copyright`. I added a link to APIENC in the copyright statement as a placeholder to show how this is done.

**Comment by ethanjli** [comment]
Widened the copyright div to the full width of its parent container. This was done in [style.css](https://www.dragonfruitproject.org/wp-admin/theme-editor.php?file=style.css&theme=DFPBestTheme&scrollto=24631) by changing max-width from 50% to 100%:

```css
.footer-socket-wrapper .copyright {
   color: #b1b6b6;
   float: left;
   font-size: 14px;
   /* max-width: 50%; */
   max-width: 100%;
}
```
